### ISSUE TITLE
Seemingly corrupted backups?

### ISSUE THREAD

**Issue by MuteTiefling** [DimensionalDevelopment/JustEnoughIDs#107]
So I was thinking of adding JustEnoughIDs to my mod pack. I installed it through Twitch, then thought better of it and disabled it in Twitch before starting minecraft.

Despite this, one of my worlds has Version: 1.13-JEID next to it and fails to load because JEID isn't loaded.

I then removed the mod entirely and restored to backups from earlier this morning, before I did anything with JEID... still the same thing. World fails to load because JEID is missing...

So I went back to yesterday's backups. All the same.

Is there perhaps some lingering config or something that I need to remove as well here? I'm not seeing anything...

**Comment by asiekierka** [comment]
Well... if the world says 1.13-JEID, it was opened at least once with JEID, and is now a JEID world!

**Comment by sam-kirby** [comment]
Also, the mod does not touch your backups. It has no mechanism to do that. Either you had JEID installed longer than you thought, or you are not actually restoring the backups correctly.

**Comment by MuteTiefling** [comment]
I love how this gets closed as I'm trying to figure things out...

I installed JEID this morning. Backups from a week ago are still showing up as 1.13 JEID when I restore them... Obviously JEID didn't go in and alter backups, how could it? But is there possibly any files I could be overlooking that would be forcing it to treat the world as a JEID world? 

As far as the restore process goes, I tried restoring through Aroma's own restore method. I also manually extracted all of the contents of multiple backups into their own new empty folders. So there should be exactly no trace of anything JEID related within the 'saves' folder. Should I be looking elsewhere for something?

**Comment by asiekierka** [comment]
What the world shows up as gets decided by the "level.dat" file in the world's save files, if I recall correctly - but the changes to the format will be largely in the region files.

**Comment by sam-kirby** [comment]
The issue was closed as it does not seem to be an issue with this mod. It was not locked, meaning you are still able to comment here and receive support, or prove me wrong.

However, following the steps you outlined, I am unable to recreate the issue. Tests carried out below.

1. Download JEID through Twitch then disable it without starting Minecraft.
Unsurprisingly a disabled mod is not loaded. Loading a world and leaving it does not cause it to have its version set to 1.13-JEID.

2. Create a world without JEID, backup using aroma, run the save with JEID enabled and finally restore in game to before JEID was enabled
Works as expected, world is identified as a 1.12 world and chunk data is not in JEID format so opens correctly.

JEID does not save anything outside of the world folder. As asie stated above, the world version information is stored in `level.dat`. Could another mod be caching this?

The stored version can be overridden. If you try to load a world that is marked as being saved in a newer version, then Minecraft will warn you that loading it may cause corruption but does not stop you. If the regions themselves were not saved with JEID then there will be no issue. If they were, then they'll fail to load.
