### ISSUE TITLE
[Bug] Crashed when open the creative inv.

### ISSUE THREAD

**Issue by SettingDust** [DimensionalDevelopment/JustEnoughIDs#114]
https://paste.ubuntu.com/p/b4NpzdB3RG/ Server (ridx: 9, widx: 9, cap: 9)
https://paste.ubuntu.com/p/kh6wFrZN3j/ Client (Print by Mixin (ridx: 0, widx: 1, cap: 256)

forge-1.12.2-14.23.5.2847-universal.jar
JustEnoughIDs-1.0.3-52-nolibs.jar

**Comment by HydrogenC** [comment]
+1, also occurs when I am playing LAN multiplayer, on which the computer that joins the game would crash when opening inventory

**Comment by HydrogenC** [comment]
This is critical, please fix it.

**Comment by sam-kirby** [comment]
There is a mixin on the client that is targeting CPacketCreativeInventoryAction, modifying the information sent such that it does not match the expectations of the server.

We have no mixins that target CPacketCreativeInventoryAction.

Without more information, I would have to conclude this is not a bug caused by this mod.

**Comment by SettingDust** [comment]
@sam-kirby It is. It's ok after downgraded.

**Comment by V-Boy** [comment]
@sam-kirby perhaps this issue should be reopened as its the first report of this happening? Dupes are #124 and #126
