### ISSUE TITLE
Conflict with Antique Atlas

### ISSUE THREAD

**Issue by beanaboston** [DimensionalDevelopment/JustEnoughIDs#27]
Seems to conflict with antique atlas. all the biomes show as deserts. other than water, that still shows as water.

with jeid and atlas
![2018-08-01_23 10 04](https://user-images.githubusercontent.com/32643374/43560412-44b9420a-95e0-11e8-9659-945b0460c2d2.png)
without jeid
![2018-08-01_23 10 12](https://user-images.githubusercontent.com/32643374/43560403-37991974-95e0-11e8-8237-c44401a416bd.png)

for now i'll be hoping i won't need to add notenoughid's (custom pack so i need to be able to remove mods). or maybe you could add a config to disable parts of the mod.

**Comment by crazyirishwrencher** [comment]
Same issue.

**Comment by justinrusso** [comment]
Was this an existing world? Were these pre-mapped areas? Through testing I've found:

1. Biome IDs shift with JEID. This means that with Antique Atlas' terribly old system for storing the texture map (pairing a texture type to a biome), biomes now have a different texture for newly mapped areas.
2. If this is with a fresh antique atlas config, I would assume that maybe it's not getting the proper data anymore for the biome to "guess" what type of biome it is and pair it with a texture type.

Really, this is Antique Atlas' issue in my eyes, but if JEID can prevent the ID shift to retain backwards compatibility for existing worlds, it's better than nothing.

Since you're starting fresh, I may recommend moving away from Antique Atlas until they update their biome texture mapping method. It creates massive headaches for pack devs as once you have the pack out, you are unable to add a new biome to your world PERIOD unless you decide to screw over anyone with an existing world.

**Comment by crazyirishwrencher** [comment]
This happened even in a new world. Thank you for taking the time and effort
to give a very thorough explanation, it is much appreciated.

**Comment by justinrusso** [comment]
Sounds like the code used to determine the biome "type" breaks with something JEID does. Possible JEID to blame on that... not sure. Either way - you can modify these in the config it generates.

**Comment by beanaboston** [comment]
What do you mean "modify it in the config it generates"? If you mean
changing the biome ids in the antique Atlas config, that doesn't work. Or
at least it didn't work when I originally reported this.

**Comment by ZombieHDGaming** [comment]
Also seems like it has been fixed on their end. If it hasn't been fixed, please let me know and I'll reopen this issue.
